### ISSUE TITLE
Get holidays where start date of holiday is not in holiday range

### ISSUE THREAD

**Issue by weisserd** [openpotato/openholidaysapi#1]
When requesting holidays for a specific time range (e.g. 1.1.23 to 1.5.23) just the holidays where the start date is in the time range are returned.

    curl -X 'GET' \
      'https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&validFrom=2023-01-01&validTo=2023-05-01&subdivisionIsoCode=DE-BW&languageIsoCode=DE' \
      -H 'accept: text/json'

It would be nice, if the holiday (in this case Winterferien 2022) would be included as well.

This would also enable the use case *Is a specific date a school holiday?* - e.g.

    https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE&validFrom=2023-01-03&validTo=2023-01-03&subdivisionIsoCode=DE-BW&languageIsoCode=DE

**Comment by fstueber** [comment]
Fixed. Please try out.

**Comment by weisserd** [comment]
Works - thanks for the quick fix!
