### ISSUE TITLE
Error in translation for Spanish holidays

### ISSUE THREAD

**Issue by bbuster2** [openpotato/openholidaysapi#10]
https://openholidaysapi.org/SchoolHolidays?countryIsoCode=ES&languageIsoCode=EN&validFrom=2023-01-01&validTo=2023-12-31

All the Christmas Holidays in the Spanish school holidays return "Christman holidays" (see typo)

Example:
`{"id":"3ea86760-1e96-49ff-9f6a-f98d31f3cfdc","startDate":"2022-12-22","endDate":"2023-01-08","type":"School","name":[{"language":"EN","text":"Christman holidays"}]`

I don't know if this happens in other countries but here i noticed it

**Comment by fstueber** [comment]
Fixed. Thank you for reporting!
