### ISSUE TITLE
Commercial use 

### ISSUE THREAD

**Issue by OrianeDalle** [openpotato/openholidaysapi#13]
Hello, 
We are looking to use your API openholidaysapi in our web application. 
First of all we need to know if it's free to use it on commercial applications ?
Then, what is the rate limite and what is your maintenance policy ?

**Comment by fstueber** [comment]
Hi, OpenHolidays API is free to use, even for commercial applications. As it is a free service, we cannot guarantee maintenance. But we try our best to keep the data of the currently supported countries up to date. In addition, you can report errors or new data at any time, ideally even initiate a pull request yourself. In the end it's a community project, the more take part, the better :-)

**Comment by fstueber** [comment]
About rate limit: I have to look up but it is a something like 1 request per sec.
