### ISSUE TITLE
Problems with text/csv

### ISSUE THREAD

**Issue by jp000** [openpotato/openholidaysapi#17]

**Comment by jp000** [comment]
When I execute this request:
curl -X 'GET' \
  'https://openholidaysapi.org/PublicHolidaysByDate?languageIsoCode=CH&date=2025-08-01' \
  -H 'accept: text/csv'

I receive a response in JSON format
 in https://openholidaysapi.org/swagger/v1/swagger.json the response for PublicHolidaysByDate can be text/csv
Only the Statics api do not provide this format

**Comment by fstueber** [comment]
That's a bug. Thanks for reporting. Will fix asap.

**Comment by fstueber** [comment]
Fixed. Please check.

**Comment by jp000** [comment]
I had a quick look at the query and it now returns the CSV format.
But there still remains a problem with the fields that get returned, they don't match the specification foud in file swagger.json (HolidayByDateResponse)
There may be other mismatches in other API that I didn't check

**Comment by fstueber** [comment]
Hmm, can you point me to an example of what doesn't match?

**Comment by jp000** [comment]
In those two requests:
'https://openholidaysapi.org/Holidays/PublicHolidaysByDate?languageIsoCode=FR&Date=2024-12-26'
'https://openholidaysapi.org/Holidays/SchoolHolidaysByDate?languageIsoCode=FR&Date=2024-12-26'
the CSV response is:
Id,Type,Name,Nationwide,Subdivisions,Comment
4aac1609-7ebd-4de5-a296-8b4193ea6cc5,Public,Saint Stephen’s Day,true,,
....

in the response, 'country' is missing.

swagger.json definition:
      "HolidayByDateResponse": {
        "required": [
          "country",
          "id",
          "name",
          "nationwide",
          "subdivisions",
          "type"
        ],
Hope this will help.

**Comment by fstueber** [comment]
Fixed. Please try again.

**Comment by jp000** [comment]
Yes, it works now. thanks
