### ISSUE TITLE
API down for header 'accept: text/calendar'?

### ISSUE THREAD

**Issue by DNC74** [openpotato/openholidaysapi#18]
It seems that since 20.12.2024 around 08:00 UTC the api does not respond properly for getting ics output.
My example: 
`curl -X 'GET' 'https://openholidaysapi.org/Holidays/PublicHolidays?countryIsoCode=DE&validFrom=2024-12-20&validTo=2024-12-31&languageIsoCode=DE&subdivisionCode=DE-BW' -H 'accept: text/calendar'  -o './feiertage.ics' ` 
returns a json string instead of an ics-format.

How to fix this?
Best regards and thank you for all the effort.

**Comment by fstueber** [comment]
Fixed. Please check.

**Comment by DNC74** [comment]
Great Frank, fix confirmed. Thank you! 
Wünsche schöne Feiertage!
