### ISSUE TITLE
Adding CORS on Server

### ISSUE THREAD

**Issue by ddsmartial** [openpotato/openholidaysapi#2]
To prevent CORS-Error when accessing the Api from Http client , enable CORS from server side

**Comment by ddsmartial** [comment]
Thanks very much. 
Do you might if I ask when the feature might probably be available? Best regards

**Comment by fstueber** [comment]
No promises. But I am working an some refactoring, including CORS. Hope do get it ready next week.

**Comment by ddsmartial** [comment]
Thanks very much 👍 .

**Comment by fstueber** [comment]
Done. Please check.

**Comment by ddsmartial** [comment]
Thanks very much. Sorry for the late reply. 
I Just had a look. And I keep getting the CORS error. 
I saw the new commit in the **src/webservice/Program.cs file**: `app.UseCors();`

I am asking myself if we should not enforce policy constraints. We have done that in some of our similar projects as follows

`app.UseCors(b =>
            {
                b.AllowAnyOrigin()
                 .AllowAnyMethod()
                 .AllowAnyHeader();
            });
`
I guess this will work.
Thanks

**Comment by fstueber** [comment]
According to this test it should work: https://cors-test.codehappy.dev/?url=https%3A%2F%2Fopenholidaysapi.org%2FCountries&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get

**Comment by fstueber** [comment]
What's the error message? And: Can you give me the exact api call including request headers?

**Comment by ddsmartial** [comment]
Sorry, my Error.
The httpHeaders should just include the Accept-Header and nothing else. 
'Accept': 'application/json'.

Now everything is working perfectly. Thanks very much 👍

**Comment by fstueber** [comment]
Ah great. Yes, Accept-Header is mandatory and only GET method is allowed for CORS
