### ISSUE TITLE
Include spanish holidays to the api

### ISSUE THREAD

**Issue by cceliberty** [openpotato/openholidaysapi#3]
Hello,

I would like to be able to retrieve Spanish holidays.

*I don't know if this is the correct place to post this question (issue).

**Comment by fstueber** [comment]
Hi, thank you for your interest in this project. The goal of the OpenHolidays API is to cover all European coutries. And yes, Spain is still missing. Are you interested in public holidays only or also in school holidays? And of course, any help is greatly appreciated.

**Comment by Kmelow** [comment]
Hi, yes school holidays would be great.

I would like to try and implement this solution but would need some guidance, especially in the `C#` department.

*I prefer contributing with my personal account

**Comment by Kmelow** [comment]
I am not sure how they are organised (I'm not from Spain  😊).
I'll check that during the weekend and post my findings here.

Thanks

**Comment by fstueber** [comment]
I am closing this issue. The right repository/place for further discussion is here: https://github.com/openpotato/openholidaysapi.data/issues
