### ISSUE TITLE
Not all holidays returned when subdivisionCode is specified

### ISSUE THREAD

**Issue by jdeus** [openpotato/openholidaysapi#4]
When specifying subdivisionCode=CH, I expect all holidays related to Vaud to be returned.

However, that's not the case.

The following call for example doesn't return 2023-05-29

`https://openholidaysapi.org/PublicHolidays?countryIsoCode=CH&validFrom=2023-01-01&validTo=2023-12-31&subdivisionCode=VD`

When subdivisionCode is not specified (only countryIsoCode=CH) 2023-05-29 is returned for Vaud.

**Comment by fstueber** [comment]
Hello, thank you for the feedback. The subdivision code must be `CH-VD` and not `VD`. Your API call only responds with all nationwide holidays as `VD` does not fit. I agree that it is a bit misleading, I will fix this (wrong subdivision code should respond with a meaningful error message)
