### ISSUE TITLE
Suggestion: Endpoint for specific date that returns holidays

### ISSUE THREAD

**Issue by BlackScreen** [openpotato/openholidaysapi#5]
Hello,
thanks for the API. One suggestion:
Could we get an endpoint where we enter a specific date and the API returns the countries etc. that do have public or school holidays on that date? This would be really handy for me.
Thanks for considering and for your work on the API! :)

**Comment by fstueber** [comment]
Hi, makes sense. Could you tell me a little bit more about your use case? Is it just for one day? Or maybe for one week as well? Thank you

**Comment by BlackScreen** [comment]
I would like to check a specific date - for example for visiting a theme park - if there are holidays in the countries around Germany. A time window would also be helpful, but I think a date would be more helpful for my use case.

**Comment by fstueber** [comment]
Hi, I have implemented two new API endpoints: PublicHolidaysByDate + SchoolHolidaysByDate. See https://openholidaysapi.org/swagger for testing and details. 

Any feedback welcomed.

**Comment by BlackScreen** [comment]
Very cool and very fast. Thank you for implementing it so quickly! :)
