### ISSUE TITLE
API Query dates limited

### ISSUE THREAD

**Issue by vandik-23** [openpotato/openholidaysapi#7]
Hi guys, 

First of all thank you for creating this API and project, it is great to have such an open API! I am very thankful!
We are using your OpenHoliday API for a university project, and would need to request  the data from 2020 to 2030 for CH, FR, DE. However I noted, that the API from the website, is only working for both public and school holidays as well if I set the dates between current year 2023 and 2025. For earlier and later years I get an error message.

I could find the actual data in CSV files on your github page, which is very helpful, however, as the requirement of our project is get data from an API I was wondering, if you are aware of this limitation, whether you would like to change it, and make the whole range of dates accessible through the API.

Thank you in advance for your reply.

**Comment by fstueber** [comment]
Hi, there is a date range limit on the API. You cannot ask for more than 3 years. In your case you have to ask for 2020-2022, 2023-2025, 2026-2028 and 2029-2031. If I have mistunderstood you, please share the HTTP request so I can look into it.

**Comment by vandik-23** [comment]
Ahh, ok, maybe this is the issue! have tried it for longer periods.  I may have overlooked this information on the website. I will try and let you know, if any issues let you know. If you do not hear from me, all worked fine!  ;) Thank you!

**Comment by fstueber** [comment]
The problem is that there is no meaningful error message about this problem. I will fix this in a future version.

**Comment by vandik-23** [comment]
Thank you!
