### ISSUE TITLE
Requesting more than three years of data results in a 500 error. 

### ISSUE THREAD

**Issue by Jet-Bee** [openpotato/openholidaysapi#8]
Requesting up to three years of data is not a problem:

curl -X 'GET' \
  'https://openholidaysapi.org/PublicHolidays?countryIsoCode=NL&languageIsoCode=NL&validFrom=2020-12-31&validTo=2023-12-31' \
  -H 'accept: text/plain'

gives the desired result.

But one day longer:
curl -X 'GET' \
  'https://openholidaysapi.org/PublicHolidays?countryIsoCode=NL&languageIsoCode=NL&validFrom=2020-12-30&validTo=2023-12-31' \
  -H 'accept: text/plain'

returns a 500 error. 

Is this due inherent limitation of the API or its underlying libraries, something that could be solved?

**Comment by fstueber** [comment]
3 years limit is by design. Please see: https://github.com/openpotato/openholidaysapi.website/issues/5
This will probably change in a future version.
